name: Composer install & unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
        symfony: ['6.4', '7.3']
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run test suite
        run: composer test
